services:
  dev:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
    command: flask run --host=0.0.0.0 --port=5000

  prod:
    build: .
    ports:
      - "5000:5000"
    command: gunicorn -w 20 -b 0.0.0.0:5000 app:app
