x-common: &common-config
  container_name: helloworld
  ports:
    - "5000:5000"

x-common-build: &common-build-config
  <<: *common-config
  build:
    context: .
    dockerfile: Dockerfile

services:
  dev:
    <<: *common-build-config
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
    command: flask run --host=0.0.0.0 --port=5000 --debug

  test:
    <<: *common-build-config

  prod:
    image: ghcr.io/knackbox/helloworld:latest

