name: Build and Push Multi-Arch Docker Image to GHCR

on:
  push:
    branches: [ main ]
  release:
    types: [published]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set image tags
        id: tags
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository }}
          TAGS="${IMAGE_NAME}:latest"

          if [[ "${{ github.event_name }}" == "release" ]]; then
            VERSION_TAG=${{ github.event.release.tag_name }}
            TAGS="$TAGS,${IMAGE_NAME}:${VERSION_TAG}"
          fi

          echo "tags=$TAGS" >> "$GITHUB_OUTPUT"

      - name: Build and push multi-arch image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.tags.outputs.tags }}
